### ISSUE TITLE
Confusion Sample Data

### ISSUE THREAD

**Issue by davidbitton** [chiefenne/JETI_EX_BUS#21]
The sample data has the following sequence from the test data:

Byte | Hex | Dec
-- | -- | --
1 | 0x3e | 62
2 | 0x03 | 3
3 | 0x28 | 40
4 | 0x42 | 66
5 | 0x31 | 49
6 | 0x20 | 32
7 | 0x40 | 64
8 | 0x1f | 31
9 | 0xdd | 221
10 | 0x2e | 46
11 | 0xe7 | 231
12 | 0x2e | 46
13 | 0xf2 | 242
14 | 0x2e | 46
15 | 0xe0 | 224
16 | 0x2e | 46
17 | 0xe0 | 224
18 | 0x2e | 46
19 | 0xe0 | 224
20 | 0x2e | 46
21 | 0xe0 | 224
22 | 0x2e | 46
23 | 0xe0 | 224
24 | 0x2e | 46
25 | 0xe0 | 224
26 | 0x2e | 46
27 | 0xe0 | 224
28 | 0x2e | 46
29 | 0xe0 | 224
30 | 0x2e | 46
31 | 0xe0 | 224
32 | 0x2e | 46
33 | 0xe0 | 224
34 | 0x2e | 46
35 | 0xe0 | 224
36 | 0x2e | 46
37 | 0xe0 | 224
38 | 0x2e | 46
39 | 0xe0 | 224
40 | 0x2e | 46
41 | 0x78 | 120
42 | 0x69 | 105

The whole thing is supposed to be 0x28 (40) long, but it's 42. The data length is supposed to be 0x20 (32), but it's 34. Any ideas? As I understand it, the last two bytes is the CRC.

The

**Comment by chiefenne** [comment]
Hi David,

you are right, the whole message should be 40 bytes, data length 32. And yes, the last two bytes are CRC.

I tried to copy the same message from the sample data, and I find it to be 40 bytes long. Maybe there happend something during copy/paste when you extracted the message.

In the printout of the sample data I did a line wrap without keeping the colon (I added this manually in the example below).

`3e:03:28:42:31:20:40:1f:dd:2e:`

`e7:2e:f2:2e:e0:2e:e0:2e:e0:2e:`

`e0:2e:e0:2e:e0:2e:e0:2e:e0:2e:`

`e0:2e:e0:2e:e0:2e:e0:2e:78:69`

Above I listed it in a way that 10 bytes are in one line for clarity.

It appears to me that your data show one `2e:e0` too much. Can you check this again.

Best regards,
Andreas

**Comment by davidbitton** [comment]
This is how I'm using the data:
```C
    const uint8_t exbus_bytes[] = {
        0x02, 0x02, 0x7d, 0xdd, 0x2e, 0xe7, 0x2e, 0xf2, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0x78, 0x69, 0x3e, 0x03, 0x28, 0x42, 0x31, 0x20, 0x40, 0x1f, 0xdd, 0x2e, 0xe7, 0x2e, 0xf2, 0x2e, 0xe0,
        0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0x78, 0x69, 0x3d, 0x01, 0x08, 0x42, 0x3a, 0x00, 0x8f, 0xe4, 0x3e, 0x03, 0x28, 0x42, 0x31, 0x20, 0x40, 0x1f, 0xdd, 0x2e, 0xe7, 0x2e, 0xf2, 0x2e, 0xe0,
        // 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0x3e, 0x03, 0x28, 0x42, 0x31, 0x20, 0x40, 0x1f, 0xdd, 0x2e, 0xe7, 0x2e, 0xf2, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0,
        // 0x2e, 0xe0, 0x2e, 0x78, 0x69, 0x3d, 0x01, 0x08, 0x42, 0x3a, 0x00, 0x8f, 0xe4, 0x3e, 0x03, 0x28, 0x42, 0x31, 0x20, 0x40, 0x1f, 0xdd, 0x2e, 0xe7, 0x2e, 0xf2, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0, 0x2e, 0xe0
    };
```

I'm not sure how or where I picked up the addition byte. In fact, I tried again and still came up w/ 42. So, I fed the code with the sample frame from the *EX Bus communication protocol* v1.21. spec doc:
```C
const uint8_t exbus_bytes[] = { 0x3E, 0x03, 0x28, 0x06, 0x31, 0x20, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x82, 0x1F, 0x4F, 0xE2 };
```
This frame is the correct length; 40. Thanks.

**Comment by chiefenne** [comment]
no further action needed
